### ISSUE TITLE
get_cookie.py依赖chrome报错只支持Ubuntu和Debian

### ISSUE THREAD

**Issue by 404name** [Superheroff/douyin_uplod#16]
【标题】get_cookie.py依赖chrome报错only Ubuntu and Debian are supported
【期望】是否只支持Ubuntu 和Debian ，如果是可否README里面注明
【报错信息】
```bash
python get_cookie.py
请输入手机号码
输入"exit"将退出服务
19xxxxxxx994
Traceback (most recent call last):
  File "/root/douyin/get_cookie.py", line 83, in <module>
    main()
  File "/root/douyin/get_cookie.py", line 78, in main
    asyncio.run(app.main())
  File "/usr/local/python3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/douyin/get_cookie.py", line 68, in main
    await self.__cookie(playwright)
  File "/root/douyin/get_cookie.py", line 31, in __cookie
    browser = await playwright.chromium.launch(channel="chrome", headless=False)
  File "/usr/local/python3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 14740, in launch
    await self._impl_obj.launch(
  File "/usr/local/python3.10/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/usr/local/python3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 62, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/python3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 492, in wrap_api_call
    return await cb()
  File "/usr/local/python3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 100, in inner_send
    result = next(iter(done)).result()
playwright._impl._errors.Error: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
Run "playwright install chrome"
00:08:16 root@iZwz98bwuk8lq9dkb9bftxZ: ~/douyin > playwright install chrome
++ arch
+ [[ x86_64 == \a\a\r\c\h\6\4 ]]
+ [[ ! -f /etc/os-release ]]
++ bash -c 'source /etc/os-release && echo $ID'
+ ID=alinux
+ [[ alinux != \u\b\u\n\t\u ]]
+ [[ alinux != \d\e\b\i\a\n ]]
+ echo 'ERROR: cannot install on alinux distribution - only Ubuntu and Debian are supported'

```

**Comment by Superheroff** [comment]
> 【标题】get_cookie.py依赖chrome报错only Ubuntu and Debian are supported
> 
> 【期望】是否只支持Ubuntu 和Debian ，如果是可否README里面注明
> 
> 【报错信息】
> 
> ```bash
> 
> python get_cookie.py
> 
> 请输入手机号码
> 
> 输入"exit"将退出服务
> 
> 19xxxxxxx994
> 
> Traceback (most recent call last):
> 
>   File "/root/douyin/get_cookie.py", line 83, in <module>
> 
>     main()
> 
>   File "/root/douyin/get_cookie.py", line 78, in main
> 
>     asyncio.run(app.main())
> 
>   File "/usr/local/python3.10/lib/python3.10/asyncio/runners.py", line 44, in run
> 
>     return loop.run_until_complete(main)
> 
>   File "/usr/local/python3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
> 
>     return future.result()
> 
>   File "/root/douyin/get_cookie.py", line 68, in main
> 
>     await self.__cookie(playwright)
> 
>   File "/root/douyin/get_cookie.py", line 31, in __cookie
> 
>     browser = await playwright.chromium.launch(channel="chrome", headless=False)
> 
>   File "/usr/local/python3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 14740, in launch
> 
>     await self._impl_obj.launch(
> 
>   File "/usr/local/python3.10/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 95, in launch
> 
>     Browser, from_channel(await self._channel.send("launch", params))
> 
>   File "/usr/local/python3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 62, in send
> 
>     return await self._connection.wrap_api_call(
> 
>   File "/usr/local/python3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 492, in wrap_api_call
> 
>     return await cb()
> 
>   File "/usr/local/python3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 100, in inner_send
> 
>     result = next(iter(done)).result()
> 
> playwright._impl._errors.Error: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
> 
> Run "playwright install chrome"
> 
> 00:08:16 root@iZwz98bwuk8lq9dkb9bftxZ: ~/douyin > playwright install chrome
> 
> ++ arch
> 
> + [[ x86_64 == \a\a\r\c\h\6\4 ]]
> 
> + [[ ! -f /etc/os-release ]]
> 
> ++ bash -c 'source /etc/os-release && echo $ID'
> 
> + ID=alinux
> 
> + [[ alinux != \u\b\u\n\t\u ]]
> 
> + [[ alinux != \d\e\b\i\a\n ]]
> 
> + echo 'ERROR: cannot install on alinux distribution - only Ubuntu and Debian are supported'
> 
> 
> 
> ```

谢谢，下次更新我会解决这个问题
